### ISSUE TITLE
Somethong wrong with out2?

### ISSUE THREAD

**Issue by zappfinger** [gleb812/pch2csd#18]
In this generated csd, I get no sound. (had to add extension .txt)
Look at line 162...

I also noted the new additions A2K and K2A. What are they for?
Richard 
[envAHD.pch2.csd.txt](https://github.com/gleb812/pch2csd/files/1844787/envAHD.pch2.csd.txt)

**Comment by ech2** [comment]
These convert between a- and k-rate signals. For example, if a red patchcord comes into blue inlet and there’s no alternative to this inlet in the polymorphic variant of this module, then the pch2csd tool will insert the A2K module just before the inlet to convert rates.

**Comment by ech2** [comment]
Regarding having no sound. Could you please provide a minimal example demonstrating the issue, please?

**Comment by zappfinger** [comment]
Can't make it much simpeler. I only use a red output to a red input and a blue output to a trigger (yellow) input. Attached the Clavia patch..
[envAHD.pch2.txt](https://github.com/gleb812/pch2csd/files/1844842/envAHD.pch2.txt)

**Comment by gleb812** [comment]
@zappfinger So far the output of EnvAHD gives a normal periodic series of signals.. So probably something's wrong between EnvAHD and Outs2. Probably K2A / A2K. I hope to locate it tomorrow!

**Comment by gleb812** [comment]
@zappfinger Richard, the problem was caused by wrong type of EnvAHD I guess. By default, EnvAHD should be k-rate module with blue outputs. It must be fixed in the template. 
I manually enlarged the size of z-space to 10, and used 10th audio channel to route audio directly from EnvAHD to Outs and it works OK. So let me fix the template and lets try it again fixed.

**Comment by gleb812** [comment]
@zappfinger BTW, have you written this EnvAHD by yourself? For some reason, the one which is in the repository looks different and unfinished.

**Comment by zappfinger** [comment]
I'm not sure. EnvAHD as a blue and a red output (all to the right)...

**Comment by gleb812** [comment]
@zappfinger you may check for instance EnvH. It also has two versions - k and a. So EnvAHD has to be copied once again with small inputs/outputs fix. @ech2 can also give some ideas on polymorphic modules.

**Comment by ech2** [comment]
Hei @zappfinger, please check the tutorial: https://github.com/gleb812/pch2csd/wiki/Making-a-new-module — it describes what we mean by polymorphic modules and how to implement them. The tutorial is a bit outdated as of now, particularly the implementation synthax is different, but the concepts described there are still valid. If you have any questions — please ask!

**Comment by gleb812** [comment]
@zappfinger  I've just check your code. Transeg is a nice try, the only sad thing is that you cannot change the stage durations during at the performance time. In case of Clavia, you can alter the attack time and it will be change on a fly. So that's why some previously made modules are a bit tricky and do not use linseg/expseg/transeg opcodes.

**Comment by zappfinger** [comment]
Ok. then it gets a bit more complicated, I have to reconsider how to do 
it...

**Comment by zappfinger** [comment]
This can be closed
