### ISSUE TITLE
idea for GUI interface

### ISSUE THREAD

**Issue by zappfinger** [gleb812/pch2csd#19]
I was just thinking, interfacing with any GUI should be rather easy!
Say we use chnget (or OSC) to get a slider value, then thanks to zkwm we can mix this with the existing connection! Should be very simple...

**Comment by gleb812** [comment]
Sure, it is. Maybe we can already start communicating with some free Clavia editor project.

**Comment by ech2** [comment]
I think the easiest way would be to reserve some MIDI CC numbers for receiving data from the GUI. This way, it’d be straightforward to implement controls in the Clavia editor and build a VST plugin using Cabbage, that would have knobs that send these MIDI messages to the Csound engine running our patch. This way we’ll reuse functions that are already available and decrease implementation complexity. And simply won’t invent bicycle.

The work on Cabbage is slowly going. I use Linux and current Cabbage version doesn’t compile plugins properly — it’s probably a minor error, because the plugins produce sound, just something wrong happens when Cabbage creates a plugin. Here’s the issue: https://github.com/rorywalsh/cabbage/issues/9

**Comment by gleb812** [comment]
Are we talking about the same things? I guess @zappfinger means interfacing with some NM editor.. @ech2 - VST, as we have discussed, should be looking like the panel of NM2 hardware, right?

**Comment by zappfinger** [comment]
I was indeed thinking on some generic editor, could be web based, 
QtCsound, etc. But maybe it is good to have some options available: 
csound channels, OSC, midi cc,..

**Comment by rorywalsh** [comment]
I've fixed the issue Eugene mentioned, so hopefully he can press on now with the development of the GUI ;)
